import type { ScoreMode } from '../audio/types.ts';

interface ScoreModeSelectorProps {
  currentMode: ScoreMode;
  onChange: (mode: ScoreMode) => void;
  disabled?: boolean;
}

const MODE_OPTIONS: { mode: ScoreMode; name: string; description: string }[] = [
  {
    mode: 'riley',
    name: 'Riley',
    description: "Terry Riley's 53 original patterns from In C (1964)",
  },
  {
    mode: 'generative',
    name: 'Generative',
    description: 'Algorithmically generated melodic cells inspired by minimalism',
  },
  {
    mode: 'euclidean',
    name: 'Euclidean',
    description: "Rhythmic patterns generated by Bjorklund's Euclidean algorithm",
  },
];

export function ScoreModeSelector({ currentMode, onChange, disabled }: ScoreModeSelectorProps) {
  return (
    <div className="score-mode-selector">
      {MODE_OPTIONS.map(({ mode, name, description }) => (
        <button
          key={mode}
          className={`score-mode-option${currentMode === mode ? ' score-mode-option--active' : ''}`}
          onClick={() => onChange(mode)}
          disabled={disabled}
          aria-pressed={currentMode === mode}
        >
          <span className="score-mode-name">{name}</span>
          <span className="score-mode-description">{description}</span>
        </button>
      ))}
    </div>
  );
}
